### ISSUE TITLE
Can you provide visual result?

### ISSUE THREAD

**Issue by xuhangc** [yousefkotp/DGUT-Flare-Removal-Using-Depth-Guided-U-Shaped-Transformer#4]
Hi, I am wondering if you can provide visual comparison results of all methods so that I don't need to run all methods again.

**Comment by yousefkotp** [comment]
Thank you for reaching out and expressing interest in the visual comparison results across different methods. Unfortunately, at this moment, I do not have a comprehensive set of visual comparison results available for immediate sharing. The comparative data and results are not stored on a personal computer or readily accessible online for direct download.

Thank you for your understanding and interest in our work. Please stay tuned for any updates or releases that might include the comparative analysis you're seeking.
