### ISSUE TITLE
how to infer with image which size is not (512, 512) ?

### ISSUE THREAD

**Issue by JingzhuT** [yousefkotp/DGUT-Flare-Removal-Using-Depth-Guided-U-Shaped-Transformer#5]

**Comment by yousefkotp** [comment]
To apply the flare removal model on images that are not of size (512, 512), you can resize the input image to (512,512) using interpolation methods like bilinear, bicubic, or nearest neighbor. However, if maintaining the aspect ratio is crucial, consider cropping the central part of the image to fit the model's input size. On the other hand, if the image is smaller than (512,512), consider padding to preserve the entire content without distortion. 

After the model has processed the resized/cropped/padded image, you might need to revert the changes to match the original image dimensions whether by resizing back or padding removal.
