### ISSUE TITLE
The pretrained model does not exist.

### ISSUE THREAD

**Issue by yangyanghao** [yousefkotp/DGUT-Flare-Removal-Using-Depth-Guided-U-Shaped-Transformer#6]
I can download dataset and other google drive links except the pretrained model. 
Can you re-upload your pretrained model? 
Thanks.

**Comment by yousefkotp** [comment]
Updated, thank you for raising this issue. You can find it [here](https://drive.google.com/file/d/13SWmwJVaRn6tUuJX2fljbrrxQSr9xVF6/view?usp=sharing)
